// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoV7q-s6FEXhvBj7mQDZFWo-n1c0Hz6J4',
    appId: '1:225002018171:web:12cd94c07a0814311199de',
    messagingSenderId: '225002018171',
    projectId: 'smt-internal',
    authDomain: 'smt-internal.firebaseapp.com',
    storageBucket: 'smt-internal.firebasestorage.app',
    measurementId: 'G-J8X9HGRWQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykb9hlZywdTElbk8z0wPgII739CQVFtc',
    appId: '1:225002018171:android:89f340cb6dff124a1199de',
    messagingSenderId: '225002018171',
    projectId: 'smt-internal',
    storageBucket: 'smt-internal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBWUumjXC9pAvT8AUivrq56AMKtH-XcQ',
    appId: '1:225002018171:ios:089a70cfd8b21fd81199de',
    messagingSenderId: '225002018171',
    projectId: 'smt-internal',
    storageBucket: 'smt-internal.firebasestorage.app',
    androidClientId: '225002018171-6lbi4dj3a887rmsmh3strs433bokmmp4.apps.googleusercontent.com',
    iosClientId: '225002018171-coo8r0mps77n47j5unghjp78ahlvoool.apps.googleusercontent.com',
    iosBundleId: 'com.logicaldevs.trackCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBWUumjXC9pAvT8AUivrq56AMKtH-XcQ',
    appId: '1:225002018171:ios:089a70cfd8b21fd81199de',
    messagingSenderId: '225002018171',
    projectId: 'smt-internal',
    storageBucket: 'smt-internal.firebasestorage.app',
    androidClientId: '225002018171-6lbi4dj3a887rmsmh3strs433bokmmp4.apps.googleusercontent.com',
    iosClientId: '225002018171-coo8r0mps77n47j5unghjp78ahlvoool.apps.googleusercontent.com',
    iosBundleId: 'com.logicaldevs.trackCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoV7q-s6FEXhvBj7mQDZFWo-n1c0Hz6J4',
    appId: '1:225002018171:web:3d5bd77a89a52dce1199de',
    messagingSenderId: '225002018171',
    projectId: 'smt-internal',
    authDomain: 'smt-internal.firebaseapp.com',
    storageBucket: 'smt-internal.firebasestorage.app',
    measurementId: 'G-4FN5MQ9JX7',
  );
}
